package com.example.hash.home.models

import com.example.hash.R

class DataSource2 {    //静态
    companion object {
        fun createDataSet(): ArrayList<BlogPost> {
            val list = ArrayList<BlogPost>()
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "不动鸣神,恒常乐土",
                    R.drawable.tmp__4,
                    "miHoYo"
                )
            )
            list.add(
                BlogPost(
                    "千手百眼,天下人间",
                    R.drawable.tmp__5,
                    "miHoYo"
                )
            )
            return list
        }
    }
}